@BASE_URL=http://localhost:8080
@JWT_TOKEN=abc
###
GET {{BASE_URL}}/ping 
###
GET {{BASE_URL}}/notes/0202c34a-e6bc-11eb-9a1d-a85e4537ab5a
###
GET {{BASE_URL}}/notes

###
POST {{BASE_URL}}/notes 
Content-Type: application/json

{
    "title":"Week 05",
    "content": "Refactor db package"
}